  build_ios:
        name: Build IOS
        runs-on: macos-latest
        env:
          TMDB_API_READ: ${{ secrets.TMDB_API_READ }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OMDB_API_KEY_FOR_SERIES: ${{ secrets.OMDB_API_KEY_FOR_SERIES }}
          OMDB_API_KEY_FOR_EPISODES: ${{ secrets.OMDB_API_KEY_FOR_EPISODES }}

        steps:
          - uses: actions/checkout@v2
          - uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.19.0'
          - run: flutter pub get
          - run: |
              echo "TMDB_API_READ=${{ secrets.TMDB_API_READ }}" > .env
              echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env
              echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> .env
              echo "OMDB_API_KEY_FOR_SERIES=${{ secrets.OMDB_API_KEY_FOR_SERIES }}" >> .env
              echo "OMDB_API_KEY_FOR_EPISODES=${{ secrets.OMDB_API_KEY_FOR_EPISODES }}" >> .env

          - run: flutter build ios --release --no-codesign
          - name: Create IPA
            run: |
              cd build/ios/iphoneos
              mkdir Payload
              cp -r Runner.app Payload
              zip -r mirarr.ipa Payload
          - name: Upload binary
            uses: actions/upload-artifact@v4
            with:
              name: ios-app
              path: build/ios/iphoneos/mirarr.ipa