name: Build Final Flutter App

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Build iOS
        run: |
          cd ios
          flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd ios
          mkdir -p Payload
          cp -r Runner.app Payload
          zip -r blackhole.ipa Payload